name: www-syake-co-jp
version: 1.0.0
category: Web
author: Syake
maintainer: info@syake.co.jp
copyright: Syake

github: Dan344/www.syake.co.jp

dependencies:
- base >=4.7 && <5
- containers
- filepath
- hakyll
- pandoc
- time

executables:
  site:
    main: site.hs
    ghc-options: -threaded
